name: publish

on:
  push:
    tags: [ 'v*' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - run: yarn install
    - run: yarn test
    - run: yarn build
    - run: |
        yarn config set registry https://registry.npmjs.org/
        yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
